//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbanhang.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Product
    {
        
     
        [Display(Name = "Số ID  ")]
        [Required(ErrorMessage = "ID sản phẩm không được để trống")]
        public int Id { get; set; }
        //
        [Display(Name = "Tên sản phẩm")]
        public string Name { get; set; }
        //
        [Display(Name = "Hình ảnh")]
        public string Avatar { get; set; }
        //
        [Display(Name = "Thể loại ID sản phẩm ")]
        public Nullable<int> CategoryId { get; set; }
        //
        [Display(Name = "Giá")]
        public Nullable<double> Price { get; set; }
        //
        [Display(Name = "Giảm giá ")]
        public Nullable<double> PriceDiscount { get; set; }
        //
           [Display(Name = "Loại ID sản phẩm ")]
        public Nullable<int> TypeId { get; set; }
           //
        [Display(Name = "Đường dẫn")]
        public string Slug { get; set; }
        //
        [Display(Name = " ID Thương hiệu")]
        public Nullable<int> Brandid { get; set; }
        //
        [Display(Name = "Đã xóa")]
        public Nullable<int> Deleted { get; set; }
        //
        [Display(Name = "Hiện lên trang chủ")]
        public Nullable<int> ShowOnHomePage { get; set; }
        //
        [Display(Name = "Đã tạo OnUtc")]
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        //
        [Display(Name = "Cập nhật OnUtc")]
        public Nullable<System.DateTime> UpdateOnUtc { get; set; }
        //
        [Display(Name = "Mô tả đầy đủ")]
        public string FullDescription { get; set; }
        //

        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
        //
    }
}
